#!/bin/sh

# This file configures the paths used by dpg4x.
# You can modify to suit your needs. 
# Read the INSTALL file for more details.

# Set the folder for default installation
DPG4X_BASE=/usr/share/dpg4x

# Path to the source files
export DPG4X_SOURCE=$DPG4X_BASE

# Path to the icon files
export DPG4X_ICONS=$DPG4X_BASE/icons

# Path to the gettext resources
export DPG4X_I18N=/usr/share/locale

# Execute the python interpreter
/usr/bin/env python "$DPG4X_SOURCE/Dpg4x.py" "$@"

